### Local Testing
### Accounts:

### Select All
GET http://localhost:3030/accounts

### Select By ID - Successful
GET http://localhost:3030/accounts/673d0ca482a76edb238cf335

### Add new Account
POST http://localhost:3030/accounts
Content-Type: application/json

{
    "firstname":"Tony",
    "lastname":"Stark",
    "password":"s+@RkR0cK2"
}

### Add another new Account
POST http://localhost:3030/accounts
Content-Type: application/json

{
    "firstname":"Bruce",
    "lastname":"Lee",
    "password":"w@Lk+Th3wayofTh3Dr@g0N"
}

### Add new Account - ERROR TEST: Test to see if the password being wrong will cause it to not be added
### Completely wrong
POST http://localhost:3030/accounts
Content-Type: application/json

{
    "firstname":"Error",
    "lastname":"Big Error",
    "password":"error"
}

### Add new Account - ERROR TEST: Test to see if the password being wrong will cause it to not be added
### Space addded
POST http://localhost:3030/accounts
Content-Type: application/json

{
    "firstname":"Error",
    "lastname":"Big Error",
    "password":"er ror"
}

### Add new Account - ERROR TEST: Test to see if the password being wrong will cause it to not be added
### Not long enough
POST http://localhost:3030/accounts
Content-Type: application/json

{
    "firstname":"Error",
    "lastname":"Big Error",
    "password":"1@"
}

### Add new Account - ERROR TEST: Test to see if the password being wrong will cause it to not be added
### Long enough, has symbol, has number, but does have a space
POST http://localhost:3030/accounts
Content-Type: application/json

{
    "firstname":"Error",
    "lastname":"Big Error",
    "password":"@erR0r2 are cool"
}

### Add new Account - ERROR TEST: Test to see if the password being wrong will cause it to not be added
### No password
POST http://localhost:3030/accounts
Content-Type: application/json

{
    "firstname":"Error",
    "lastname":"Big Error"
}

### Update Account
PUT http://localhost:3030/accounts/673e6eaaf4b63d2b9ef1f8b7
Content-Type: application/json

{
    "firstname":"Iron",
    "lastname":"Man",
    "password":"s+@RkR0cK2"
}

### Revert Account
PUT http://localhost:3030/accounts/673e6eaaf4b63d2b9ef1f8b7
Content-Type: application/json

{
    "firstname":"Tony",
    "lastname":"Stark",
    "password":"s+@RkR0cK2"
}

### Update another Account
PUT http://localhost:3030/accounts/673e7d55ed8bf5d5ec97b430
Content-Type: application/json

{
    "firstname":"The",
    "lastname":"Dragon",
    "password":"b3C0m3L1K3tH3Dr@g0n"
}

### Revert Account
PUT http://localhost:3030/accounts/673e7d55ed8bf5d5ec97b430
Content-Type: application/json

{
    "firstname":"Bruce",
    "lastname":"Lee",
    "password":"w@Lk+Th3wayofTh3Dr@g0N"
}

### Update another Account
PUT http://localhost:3030/accounts/673d0ca482a76edb238cf335
Content-Type: application/json

{
    "firstname":"MyLittleTest",
    "lastname":"TestMe",
    "password":"t3s+Y0urprojects"
}

### Update Error Test
### Update an account with an invalid password
PUT http://localhost:3030/accounts/673d0ca482a76edb238cf335
Content-Type: application/json

{
    "firstname":"MyLittleTest",
    "lastname":"TestMe",
    "password":"t3s+Y0"
}

### Update Error Test
### Update an account with no firstname
PUT http://localhost:3030/accounts/673d0ca482a76edb238cf335
Content-Type: application/json

{
    "lastname":"TestMe",
    "password":"t3s+Y0urprojects"
}

### Update Error Test
### Update an account with no lastname
PUT http://localhost:3030/accounts/673d0ca482a76edb238cf335
Content-Type: application/json

{
    "firstname":"MyLittleTest",
    "password":"t3s+Y0urprojects"
}

### Update Error Test
### Update an account with no password
PUT http://localhost:3030/accounts/673d0ca482a76edb238cf335
Content-Type: application/json

{
    "firstname":"MyLittleTest",
    "lastname":"TestMe"
}

### Update Error Test
### Update an account to have a matching password as another account
PUT http://localhost:3030/accounts/673d0ca482a76edb238cf335
Content-Type: application/json

{
    "firstname":"TestTony",
    "lastname":"Test",
    "password":"w@Lk+Th3wayofTh3Dr@g0N"
}

### Revert Account
PUT http://localhost:3030/accounts/673d0ca482a76edb238cf335
Content-Type: application/json

{
    "firstname":"TestTony",
    "lastname":"Test",
    "password":"t3s+Y0urpr@jects"
}

### Delete test

### Create new account to delete
POST http://localhost:3030/accounts
Content-Type: application/json

{
    "firstname":"DeleteDave",
    "lastname":"DeleteMe",
    "password":"d3L3+3me"
}

### Delete the new account - make sure to update the id in the url
DELETE http://localhost:3030/accounts/6746adfe4bbec5e9a7961d78





### ORDERS:
### View All Orders
GET http://localhost:3030/orders

### View Order by ID
GET http://localhost:3030/orders/673e9d727e0ff142abed5a2d

### Create new Order
POST http://localhost:3030/orders
Content-Type: application/json

{
    "size":"small",
    "sauce":"Garlic Sauce",
    "toppings":"Pepperoni, Mushrooms, Sausage",
    "drink":"Dr.Kelp",
    "deliveryAddress":"9999 Testway S.",
    "deliveryTime":"5:00 PM",
    "price":9.99,
    "orderAccountId":"673d0ca482a76edb238cf335"
}

### Create another Order - Tony Stark Order
POST http://localhost:3030/orders
Content-Type: application/json

{
    "size":"large",
    "sauce":"Red Sauce",
    "toppings":"Pepperoni",
    "drink":"Sprite",
    "deliveryAddress":"9991 StarkWay S.",
    "deliveryTime":"7:00 PM",
    "price":15.99,
    "orderAccountId":"673e6eaaf4b63d2b9ef1f8b7"
}

### Create another Order - Test default values
POST http://localhost:3030/orders
Content-Type: application/json

{
    "size":"large",
    "deliveryTime":"8:00 PM",
    "price":15.99,
    "orderAccountId":"673e6eaaf4b63d2b9ef1f8b7"
}

### Update Order
PUT http://localhost:3030/orders/673e9d727e0ff142abed5a2d
Content-Type: application/json

{
    "size":"large",
    "sauce":"Garlic Sauce",
    "toppings":"Pepperoni, Mushrooms",
    "drink":"Diet Coke",
    "deliveryTime":"5:30 PM",
    "price":15.99,
    "orderAccountId":"673d0ca482a76edb238cf335"
}

### Revert Order
PUT http://localhost:3030/orders/673e9d727e0ff142abed5a2d
Content-Type: application/json

{
    "size":"small",
    "sauce":"Garlic Sauce",
    "toppings":"Pepperoni, Mushrooms, Sausage",
    "drink":"Dr.Kelp",
    "deliveryAddress":"9999 Testway S.",
    "deliveryTime":"5:00 PM",
    "price":9.99,
    "orderAccountId":"673d0ca482a76edb238cf335"
}

### Create a test one to delete
POST http://localhost:3030/orders
Content-Type: application/json

{
    "size":"delete",
    "sauce":"Delete Sauce",
    "toppings":"Delete",
    "drink":"Delete Cola",
    "deliveryAddress":"12 Delete E.",
    "deliveryTime":"12:00 AM",
    "price":5.99,
    "orderAccountId":"deleteME"
}

### Delete the test order - make sure to update the id in the url
DELETE http://localhost:3030/orders/673ea0ab4a34eb14239fa1d7